version: '3'
services:
  backend:
    build: ./backend
    ports:
      - "5000:5000"
    environment:
      - MONGO_URI=mongodb+srv://taskuser:dncwYlCDyfDm7CCs@cluster0.indozgm.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
